on:
  push:
    tags: debian/*

jobs:
  build-ubuntu-source:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ppa_url: [ "ppa:ppa-verse/embedded" ]
        distro:  [ focal, jammy, lunar, mantic ]

    steps:
      - uses: actions/checkout@v4
      - env:
          KEY: ${{ secrets.UBUNTU_SIGNING_KEY }}
        run: echo -n "$KEY" | base64 --decode | gpg --import

      - run: sudo apt-get -qq update && sudo apt-get -qq upgrade && sudo apt-get -qq install devscripts dput-ng
      - run: sudo apt-get -qq build-dep .

      - run: sed -re "1 s/\(([^)]+)\) ([^;]+)/\(\1~${{ matrix.distro }}\) ${{ matrix.distro }}/" -i debian/changelog
      - env:
          KEY_ID: ${{ secrets.UBUNTU_SIGNING_KEY_ID }}
        run: dpkg-buildpackage --build=source --sign-key=$KEY_ID

      - run: dput ${{ matrix.ppa_url }} ../*.changes
